language: elixir
# Test policy, where possible:
#  - should run on 3 latest minor Elixir releases.
#  - should run on 2 latest major OTP releases.
elixir:
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 21
  - 22

# Certain older Elixir releases do not fair well with newer
# OTP releases, when that is the case they can be exluded
# from the matrix here:
# matrix:
#   exclude:
#     - elixir: 1.x.x
#       otp_release: 20.x

sudo: false # To use faster container based build environment
script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

notifications:
  recipients:
    - mail@djm.org.uk
