language: elixir
# Test policy, where possible:
#  - should run on 3 latest minor Elixir releases.
#  - should run on 2 latest major OTP releases.
elixir:
  - 1.5.2
  - 1.4.5
  - 1.3.4
otp_release:
  - 19.3
  - 20.1

# Certain older Elixir releases do not fair well
# with the OTP 20 release, so they are excluded.
matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.1

sudo: false # To use faster container based build environment
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mail@djm.org.uk
