language: elixir
# Test policy:
#  - should run on 3 latest minor Elixir releases.
#  - should run on 2 latest major OTP releases.
elixir:
  - 1.3
  - 1.2.6
  - 1.1.1
otp_release:
  - 19.0
  - 18.3
matrix:
  exclude:
    # 1.1 Does not run on v19 OTP.
    - elixir: 1.1.1
      otp_release: 19.0
sudo: false # To use faster container based build environment
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mail@djm.org.uk
