name: TableRex CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Official support is for latest 3 minor Elixir
        # versions & latest 2 major OTP releases.
        elixir: ["1.13", "1.14", "1.15"]
        otp: ["25", "26"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install dependencies
        run: mix deps.get

      - name: Compile & error on warning
        run: mix compile --warnings-as-errors

      - name: Check code is formatted
        run: mix format --check-formatted

      - name: Run the test suite
        run: mix test
